version: "2.4"

services:
    test-app:
        build: .
        container_name: php-cli
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - test-network
        depends_on:
            test-db:
                condition: service_healthy

    test-db:
        image: mysql:8
        container_name: test-mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: payroll_test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks:
            - test-network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

networks:
    test-network:
        driver: bridge
