version: "2.4"

services:
    app:
        build: .
        container_name: php-upstream
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: oidit
            MYSQL_DATABASE: payroll
            MYSQL_USER: tidio
            MYSQL_PASSWORD: oidit
        expose:
            - 3306
        ports:
            - "3306:3306"
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10

networks:
    app-network:
        driver: bridge
