parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    app.generate_payroll_report_command:
        class: App\Infrastructure\Symfony\Command\GeneratePayrollReport
        public: true
        tags:
            - { name: 'console.command', command: 'app:generate-payroll-report' }
