services:
    test.test_helper:
        class: Tests\Functional\TestHelper
        arguments:
            - '@app.clock'
            - '@doctrine.dbal.default_connection'
            - '@messenger.default_bus'
        public: true

    app.clock:
        class: Tests\Fake\Clock
